image: node:10.16.0

services:
  - postgres:latest

variables:
  # Configure postgres service (https://hub.docker.com/_/postgres/)
  POSTGRES_DB: shuri_test
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ''

stages:
  - build
  - connect
  - lint
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

connecting_db:
  stage: connect
  image: postgres
  script:
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"

eslint:
  stage: lint
  script:
    - npm run lint
run_tests:
  stage: test
  environment: test
  script:
    - npm test
